### PR TITLE
Argument order irrelevant/ sensor parsing improved

### PR DESCRIPTION
**Pull request by onkobu**
- -s/ --sensor first does not ignore following -c/ -w anymore
- current sensor's multiline output without adapter and temperatur in 2nd line

### CODE REVIEW

**Comment by onkobu** [comment]
Output of `sensors` on my machine(s) looks like

```
k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +58.9°C  (high = +70.0°C)
                       (crit = +105.0°C, hyst = +97.5°C)
```

With -A the line Adapter can be suppressed but the extraction with grep and head -n1 doesn't work well. The second line starts with very different values depending on the architecture. It might also look like this:

```
k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +27.0°C  (high = +70.0°C)
Tctl:         +27.0°C  
```

That's why I used `sed '2 p'` to print the second line. This ought to be tested on other architectures as well, before merging.

**Comment by jackbenny** [comment]
Hi!

Thank you for your work on the project and the pull request; highly appreciated!

However, I will need some time to look into this. Out of the box, the code didn't work on my systems (Debian 10 on x86_64). What machines and distros do you use?

**Comment by onkobu** [comment]
I ran this on Gentoo Linux. I assume it depends on combination of kernel, its modules and lmsensors. That's why I added the plain output of sensors.

I could also split this in two: order of arguments irrelevant; simply moving the function call after the while. Second a conditional handling of sensors' output. But I don't know what it looks like on your side. I assume it is a single line with values in columns? Only guessing based on the head -n1 in the pipe expression.

**Comment by jackbenny** [comment]
Sorry for the late reply, it's been a busy week.

I'm using lm-sensors-3.5.0 and kernel 4.19.0. My output looks like this:

```
pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +67.5°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +62.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:        +59.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:        +59.0°C  (high = +80.0°C, crit = +100.0°C)
Core 2:        +59.0°C  (high = +80.0°C, crit = +100.0°C)
Core 3:        +58.0°C  (high = +80.0°C, crit = +100.0°C)

```

**Comment by shakalandy** [comment]
Thanks for the fix @onkobu - having the same problem with icinga2 and default command over here.

Could it be, that in the PR the "grep" is missing after "sensors -A"? This does not work over here, and addiding it won't help in searching for specific sensors.

But the order is no irrelevant, which is great, thanks!

**Comment by onkobu** [comment]
I use check_temp.sh with dedicated sensor name, e.g. `pch_skylake-virtual-0`. This yields an output of

```
pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +67.5°C  
```

First I added -A to `sensors` to omit the line starting with `Adapter`. Output then becomes

```
pch_skylake-virtual-0
temp1:        +67.5°C  
```

And from this output `sed -n 'p 2'` ought to print only the 2nd line…I'll change the PR so it still has the classic grep-expression and re-work my attempt so it is more reliable.

**Comment by onkobu** [comment]
Added -n to switch between classic and new filter. I also pulled the process-call back into the argument loop so multiple sensors are rendered correctly. My first attempt only printed out the last sensor. It is now possible to change argument order quite flexible:

```
# still using default sensor
check_temp.sh -w 60 -c 75
check_temp.sh -n  -w 65 --sensor k10temp-pci-00c3 -c 75 -w 70 -c 90 --sensor radeon-pci-0008,GPU
check_temp.sh --sensor k10temp-pci-00c3,CPU -w 65 -c 75 -w 70 -c 90 --sensor radeon-pci-0008,GPU
check_temp.sh -n  -w 65 -c 75  --sensor k10temp-pci-00c3  -w 70 -c 90 --sensor radeon-pci-0008,GPU
```

The corner case of combining default sensor CPU with another doesn't work anymore:

```
check_temp.sh -w 60 -c 75  -w 70 -c 90 --sensor radeon-pci-0008,GPU
```

I'll check Icinga2's behavior this afternoon. My instance only requests a single temperature value. Didn't check Icinga's behavior with multiple sensor requests. Hopefully it doesn't sort arguments alphabetically ;-).

**Comment by shakalandy** [comment]
Looks good to me:

```
 # sensors
pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +34.0°C

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +58.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:        +43.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:        +58.0°C  (high = +80.0°C, crit = +100.0°C)
Core 2:        +46.0°C  (high = +80.0°C, crit = +100.0°C)
Core 3:        +44.0°C  (high = +80.0°C, crit = +100.0°C)
``` 

``` 

./check_temp '--sensor' 'Core 0' '-c' '75' '-w' '65' '--sensor' 'Core 1' '-c' '75' '-w' '65' '--sensor' 'temp1' '-c' '75' '-w' '65'
TEMPERATURE OK - Core 0 has temperature: +48.0°C, Core 1 has temperature: +46.0°C, temp1 has temperature: +34.0°C | Core 0=48;65;75 Core 1=46;65;75 temp1=34;65;75
``` 

empty run does also work - should return the help page? But this is cosmetics?
``` 
 /usr/lib/nagios/plugins # ./check_temp
TEMPERATURE OK -  |
```

**Comment by shakalandy** [comment]
And i hoped that i might work with multiple sensors - with the same warning/critical threshold:

```
./check_temp.sh [-n] -w 65 -c 75 --sensor CPU -w 75 -c 85 --sensor temp1,GPU
root@web01 /usr/lib/nagios/plugins # ./check_temp '--sensor' temp1 '-c' '75' '-w' '65'
TEMPERATURE OK - temp1 has temperature: +33.5°C | temp1=33;65;75
root@web01 /usr/lib/nagios/plugins # ./check_temp '--sensor' temp1,'Core 0' '-c' '75' '-w' '65'
TEMPERATURE OK - Core 0 has temperature: +33.5°C | Core 0=33;65;75
```

**Comment by onkobu** [comment]
> And i hoped that i might work with multiple sensors - with the same warning/critical threshold

Indeed this was a use case (print_usage) my changes broke. Fixed it.

In addition I tried this with at least Debian, Ubuntu and Linux Mint (in addition to Gentoo). All have exactly the same output of `sensors` on the same hardware. As far as I remember only one of the distributions came with a 4.19-kernel. Would be great to have a check on one of the BSDs. I expect no differences if the same version of lm-sensors is used.

Thanks for the patience and guiding comments. I'll think of a testing scenario for this and contribute this in a separate pull request.

**Comment by jackbenny** [comment]
Wow! A huge thank you for all your hard work on this @onkobu :+1: I have tested it tonight and everything seems to be working just fine.
A huge thank you @shakalandy for all your input!

I have added both of you to the THANKS file :1st_place_medal:

**Comment by shakalandy** [comment]
Should this one work now with the Main branch?

```
./check_temp '--sensor' temp1,'Core 0' '-c' '75' '-w' '65'
TEMPERATURE OK - Core 0 has temperature: +34.0°C | Core 0=34;65;75
``` 
Can see only one in the output :(

Thanks!

**Comment by onkobu** [comment]
```
./check_temp '--sensor' temp1,'Core 0' '-c' '75' '-w' '65'
```

There's a lot of strange quoting going on but from Bash's perspective this ought to mean the same as:

```
./check_temp --sensor "temp1,Core 0" -c 75 -w 65
```

And according to the parsing of check_temp this renames sensor temp1 to Core 0 in the output and sets critical to 75 and warning to 65. Whether with or without single quotes doesn't matter for --sensor and the like. But I can think of Bash versions that treat `temp1,'Core 0'` a little bit different. On my side (Gentoo, Linux Mint/ Ubuntu/ Debian) this always turned out correct:

```
check_temp.sh '--sensor' k10temp-pci-00c3,'BO OH' -c 75 -w 65
TEMPERATURE OK - BO OH has temperature: +29.0°C | BO OH=29;65;75
```

If you want multiple sensors to be checked use multiple `--sensor` arguments (need to use -n for new filter otherwise sensor output cannot be parsed – reason for my PR still keeping classic parsing):

```
$> ./check_temp.sh -n --sensor radeon-pci-0008,GPU -w 65 -c 75 --sensor k10temp-pci-00c3,CPU -w 60 -c 75

TEMPERATURE OK - GPU has temperature: +54.0°C, CPU has temperature: +53.2°C | GPU=54;65;75 CPU=53;65;75
```

**Comment by shakalandy** [comment]
@onkobu Yep, you're right, it's from "icinga2" inspect feature.
Did you try having multiple sensors in icinga2 this way?

I think the default ITL can't handle that, right?

**Comment by onkobu** [comment]
> I think the default ITL can't handle that, right?

I'm doing exactly this with CPU and GPU whereas the latter doesn't make any sense on the headless system – builtin GPU.

Icinga doesn't care about the message part as long as it receives a correct error code, so "OK CPU has temperature x, GPU has temperature y" is fine and also temperature triggering works. (It was quite hard to affect the thermal zones correctly without BIOS help. I took a heat gun pointing at the CPU cooler and a thermocouple sticked to the opposite side to gently push it to warning of CPU and later warning of GPU a little later but before critical of CPU.)

Merging the multiple sensors to a single state happens in check_temp.sh/ commands in general.

The more interesting part was rendering the performance metrics for example with pnp4nagios which always happens in distinct diagrams. I already got a little upset not to have curves layered in a single diagram. A PHP-compatibility issue (in pnp4nagios) is also already pending. A fork mitigating a few other annoyances already exists (like strange units kGB for Terabyte disks).

**Pull request merged**
